# Generated by Django 5.2 on 2026-03-27 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_time',
            field=models.BooleanField(default=True),
        ),
    ]
