# Generated by Django 5.2 on 2026-04-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_product_systemstatistic_workflow_and_more'),
        ('api', '0005_product'),
    ]

    operations = [
    ]
