# Generated by Django 5.2 on 2026-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report_slug_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
