# Generated by Django 5.2 on 2026-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_category_requested_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('uptime_pct', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=12)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
