# Generated by Django 5.2 on 2026-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Finance', 'Finance'), ('Inventory', 'Inventory'), ('HR', 'HR'), ('IT', 'IT')], default='', max_length=20),
        ),
    ]
