# Generated by Django 5.2 on 2026-05-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FURNITURE', 'Furniture'), ('LIGHTING', 'Lighting'), ('ACCESSORIES', 'Accessories'), ('GENERAL', 'General')], default='GENERAL', max_length=24),
        ),
    ]
