# Generated by Django 5.2 on 2026-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Lighting', 'Lighting'), ('Accessories', 'Accessories')], default='Electronics', max_length=24),
        ),
    ]
