# Generated by Django 5.2 on 2026-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Individual', 'Individual')], default='Individual', max_length=20),
        ),
    ]
