# Generated by Django 5.2 on 2026-05-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_report_options_report_created_at_and_more'),
        ('api', '0012_add_customer_contact_name_tier'),
    ]

    operations = [
    ]
