# Generated by Django 5.2 on 2026-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_conversationsession_conversationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowlog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='workflowlog',
            name='trigger_input',
        ),
        migrations.RemoveField(
            model_name='workflowlog',
            name='trigger_result',
        ),
        migrations.AddField(
            model_name='workflow',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='actions_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='trigger_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('STOCK_BELOW_MINIMUM', 'Stock Below Minimum'), ('NEW_ORDER_RECEIVED', 'New Order Received'), ('DAILY_AT_TIME', 'Daily At Time'), ('WEEKLY_AT_TIME', 'Weekly At Time'), ('NEW_IT_TICKET', 'New IT Ticket'), ('CONTRACT_EXPIRES', 'Contract Expires'), ('ORDER_EXCEEDS_THRESHOLD', 'Order Exceeds Threshold')], default='', max_length=64),
        ),
    ]
