# Generated by Django 5.2 on 2026-05-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_category'),
        ('api', '0015_workflow_schema_v2'),
    ]

    operations = [
    ]
