# Generated by Django 5.2 on 2026-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20260514_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Lighting', 'Lighting'), ('Accessories', 'Accessories')], default='Electronics', max_length=24),
        ),
    ]
